### ISSUE TITLE
관리자페이지 - Thymeleaf 코드 제거

### ISSUE THREAD

**Issue by pyo92** [pyo92/project-lottery#189]
최초에는 새고로침 시, 목록 자체가 바뀔 수 있는 몇몇 탭 때문에 이슈를 발행했었다.

점점 코드 양이 증가하고, 복잡해지면서 유지보수하기가 힘들어졌다.
향후 고도화 시, 유지보수를 용이하게 하기 위해 front-end / back-end 를 분리하기로 결정했다.

그 초석으로 이번에 개발하는 관리자 페이지를 시작으로 Thymeleaf 를 사용하기 않기로 했다.
결론적으로 이전 이슈에서 작업했던 결과물에 대한 Thymeleaf 코드를 걷어내는 작업이다.

* [ ] ~~공통  (header, footer)~~ -> 공통 영역은 추후 front end 분리 시, 할 예정
* [x] user 탭
* [x] api 탭 - completed by [#186]
* [x] selenium 탭 - completed by [#183]
* [x] redis 탭 - completed by [#183]

**Comment by pyo92** [comment]
향후 front-end 분리를 위한 시작이기도 하다.
